- Content.Server/Radio/Components/HeadsetComponent.cs
- Content.Server/Radio/EntitySystems/HeadsetSystem.cs
- Content.Server/_Afterlight/Worldgen/Components/RadioInterferingChunkComponent.cs
- Content.Server/_Afterlight/Worldgen/Systems/RadioInterferingChunkSystem.cs
- Content.Server/_Citadel/Worldgen/WorldgenCVars.cs
- Resources/Locale/en-US/_Afterlight/headset.ftl
- Resources/Prototypes/_Afterlight/World/Biomes/basic.yml
- Resources/Prototypes/_Afterlight/World/config.yml
Prevents headsets from transmitting.
> Add radio interference.

- Content.Server/_Afterlight/Loot/Components/RandomReagentFillComponent.cs
- Content.Server/_Afterlight/Loot/ReagentSpawnCollection.cs
- Content.Server/_Afterlight/Loot/Systems/RandomReagentFillSystem.cs
- Resources/Prototypes/_Afterlight/Entities/World/Chemistry/bottles.yml
- Resources/Prototypes/_Afterlight/Entities/World/Crates/loot.yml
- Resources/Prototypes/_Afterlight/Entities/World/Debris/asteroids.yml
- Resources/Prototypes/_Afterlight/Entities/World/Debris/base_debris.yml
- Resources/Prototypes/_Afterlight/Entities/World/Debris/wrecks.yml
- Resources/Prototypes/_Afterlight/Entities/World/Spawners/salvage.yml
- Resources/Prototypes/_Afterlight/World/Biomes/basic.yml
Afterlight has unique requirements for salvage loot tables, this changes them.
> Redoes loot tables.

- Content.Client/_Afterlight/Generator/GeneratorWindow.xaml.cs
- Content.Server/_Afterlight/Generator/GeneratorSystem.cs
- Content.Shared/_Afterlight/Generator/FuelGeneratorComponent.cs
- Resources/Maps/_Afterlight/Vessels/forge.yml
- Resources/Prototypes/Catalog/VendingMachines/Inventories/salvage.yml
- Resources/Prototypes/_Afterlight/Entities/World/Debris/wrecks.yml
- Fixed generators accepting negative or massive inputs.
- Fixed the inaccessibility of engineer's goggles, they're now in the salvage vendor.
- Replaced the Forge's generator with a plasma gen.
- CrateSalvageEquipment spawns on wrecks with low odds again.
> Fix several issues.

- Content.Server/_Afterlight/Worldgen/Components/BlueprintPlacerComponent.cs
- Content.Server/_Afterlight/Worldgen/Components/StructurePlacementComponent.cs
- Content.Server/_Afterlight/Worldgen/Systems/BlueprintPlacerSystem.cs
- Content.Server/_Afterlight/Worldgen/Systems/StructurePlacementSystem.cs
- Content.Shared.Database/LogType.cs
- Resources/Maps/_Afterlight/AI/AIScout.yml
- Resources/Prototypes/_Afterlight/Entities/World/Spawners/wrecks.yml
- Resources/Prototypes/_Afterlight/World/config.yml
adds basic structure generation.
> Al structures

- Content.IntegrationTests/PoolManager.cs
- Content.Server/_Afterlight/AfterlightCVars.cs
- Content.Server/_Afterlight/Story/StoryManagementSystem.cs
Handles saving and restoring the game's story.
> Al story flags

- Content.Server/_Afterlight/Story/StoryManagementSystem.cs
> Imagine testing code.

- Content.Server/_Afterlight/Worldgen/Systems/StructurePlacementSystem.cs
- Resources/Prototypes/_Afterlight/Entities/World/Spawners/wrecks.yml
- Resources/Prototypes/_Afterlight/World/config.yml
also spawn more structures for testing.
> Fix structure gen a little

- Content.Server/_Afterlight/Research/Components/AutoRenameResearchServerComponent.cs
- Content.Server/_Afterlight/Research/Systems/AutoRenameResearchServerSystem.cs
- Resources/Prototypes/Entities/Structures/Machines/research.yml
> Makes the R&D server automatically rename to match it's parent station.

- Content.Server/Solar/EntitySystems/PowerSolarSystem.cs
> Nerf solars.

- Content.Server/_Afterlight/Research/Components/AutoRenameResearchServerComponent.cs
- Content.Server/_Afterlight/Research/Systems/AutoRenameResearchServerSystem.cs
- Resources/Prototypes/Entities/Structures/Machines/research.yml
- Resources/Prototypes/_Afterlight/Entities/World/Crates/loot.yml
- Resources/Prototypes/_Afterlight/Entities/World/Debris/wrecks.yml
> Al parts loot

- Content.Server/_Afterlight/Components/FiberousComponent.cs
- Resources/Maps/_Afterlight/Vessels/forge.yml
- Resources/Prototypes/Catalog/Research/technologies.yml
- Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
- Resources/Prototypes/Entities/Objects/Materials/materials.yml
- Resources/Prototypes/Entities/Objects/Specific/Hydroponics/leaves.yml
- Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Entities/Structures/soil.yml
- Resources/Prototypes/Recipes/Lathes/electronics.yml
- Resources/Prototypes/Recipes/Reactions/chemicals.yml
- Resources/Prototypes/_Afterlight/Chemistry/production_reactions.yml
- Resources/Prototypes/_Afterlight/Construction/Recipes/cloth.yml
- Resources/Prototypes/_Afterlight/Construction/soil.yml
- Resources/Prototypes/_Afterlight/Entities/World/Debris/wrecks.yml
> Assorted changes.

- Resources/Maps/_Afterlight/Vessels/amalgam.yml
- Resources/Prototypes/_Afterlight/Maps/Vessels/amalgam.yml
**Media**
**Changelog**
:cl:
- add: Added Amalgam, a new small industrial ship.
> Amalgam Ship

- Content.Server/_Afterlight/Components/FiberousComponent.cs
- Resources/Maps/_Afterlight/Vessels/forge.yml
- Resources/Prototypes/Catalog/Research/technologies.yml
- Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
- Resources/Prototypes/Entities/Objects/Materials/materials.yml
- Resources/Prototypes/Entities/Objects/Specific/Hydroponics/leaves.yml
- Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Entities/Structures/soil.yml
- Resources/Prototypes/Recipes/Lathes/electronics.yml
- Resources/Prototypes/Recipes/Reactions/chemicals.yml
- Resources/Prototypes/_Afterlight/Chemistry/production_reactions.yml
- Resources/Prototypes/_Afterlight/Construction/Recipes/cloth.yml
- Resources/Prototypes/_Afterlight/Construction/soil.yml
- Resources/Prototypes/_Afterlight/Entities/World/Crates/loot.yml
- Resources/Prototypes/_Afterlight/Entities/World/Debris/wrecks.yml
- Resources/Prototypes/_Afterlight/World/Biomes/basic.yml
- Resources/Prototypes/_Afterlight/World/config.yml
> i made an extra commit to a finished branch

- Content.Client/_Afterlight/Generator/GeneratorWindow.xaml.cs
> Fix generators reporting a target power of 0.

- Resources/Maps/_Afterlight/Vessels/amalgam.yml
**Media**
**Changelog**
:cl:
- tweak: Slightly tweaked the contents and fixed power gen and blast doors on Amalgam.
> Amalgam Tweaks

- Content.Server/Gravity/GravityGeneratorSystem.cs
- Content.Server/Research/Systems/ResearchSystem.Server.cs
- Content.Server/Research/Systems/ResearchSystem.cs
- Content.Server/_Afterlight/Story/AbandonedShipSystem.cs
- Content.Shared/CCVar/CCVars.cs
- Resources/Prototypes/Catalog/Fills/Boxes/emergency.yml
- Resources/Prototypes/Entities/Clothing/Masks/base_clothingmask.yml
- Resources/Prototypes/Entities/Objects/Specific/Medical/hypospray.yml
- Resources/Prototypes/Entities/Objects/Tools/gas_tanks.yml
- Resources/Prototypes/Entities/Objects/Tools/tools.yml
- Resources/Prototypes/_Afterlight/Entities/Stacks/fuels.yml
- Resources/Server Info/AL_Rules.txt
adds stuff to survival box, makes ships start dead.
> Update rules and make it easier to recover a dead ship.

- Resources/Prototypes/Catalog/VendingMachines/Inventories/salvage.yml
_Murder_
**Media**
**Changelog**
Not notable enough, no fun.
> Remove The Handheld Radio From The Salvage Vendor

- Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
**Media**
**Changelog**
:cl:
- tweak: All the items in head lockers have been reduced to simple cosmetic items.
> Reduced Head Locker Fills

- Content.Server/Botany/Components/PlantHolderComponent.cs
- Content.Server/Botany/Systems/PlantHolderSystem.cs
- Content.Server/Nutrition/Components/HungerComponent.cs
- Resources/Prototypes/_Afterlight/Entities/World/Debris/wrecks.yml
botany go slower but hungy go slower too
> the hungy update (Nerf botany significantly while also buffing it, wait what)

- Resources/Prototypes/Catalog/Research/technologies.yml
> Al remove more items

- Resources/Prototypes/Entities/Structures/Power/smes.yml
- Resources/Prototypes/Entities/Structures/Power/substation.yml
> Buff the SMES and substation.
